### ISSUE TITLE
Insert GUID shortcut is the same as the fold shortcut

### ISSUE THREAD

**Issue by QubitCabbit** [heaths/vscode-guid#12]
both are 
`Ctrl + Shift + [`

**Comment by heaths** [comment]
It's always been this way (more like `Ctrl+{`, which is the same as `Ctrl+Shift+[`). VSCode appears to have broken it, though if I attempt to repro I see it still maps to my extension. I recommend changing your _keybindings.json_ file. I wouldn't change the keybinding from what it has been all this time if people have been using it, so people changing their own preferences makes more sense I think.
