### ISSUE TITLE
how to generate uuid(randomly) as a part of html snippet in Visual Studio code?

### ISSUE THREAD

**Issue by syedirfan7** [heaths/vscode-guid#15]
I want to generate an HTML tag in VSCode when it type "_coo_" it should give me a suggestion and when pressed enter needs to give the below tag with the random value of uuid. `<Cool uuid = "xxxxx-xxxx-xxxxx-xxxxxxx" id="someId" class= "someClass" />`

**Comment by heaths** [comment]
This extension only generates GUIDs. Snippets containing GUIDs are out of scope. I could expose a public API that other extensions could use, but honestly the GUID generation is the only interesting part and done solely by the `uuid` package snippet extensions could use more easily than taking a dependency on another VSCode extension.
