### ISSUE TITLE
Only Uppercase GUID

### ISSUE THREAD

**Issue by BrianDevKit** [heaths/vscode-guid#21]
I can't get only uppercase GUIDs when setting 
insertGuid.showLowercase = false and insertGuid.showUppercase = true

**Comment by heaths** [comment]
Just to confirm, you're seeing both upper- and lowercase GUIDs when those options set as stated, correct?

**Comment by BrianDevKit** [comment]
Yes.
![InsertGuid](https://user-images.githubusercontent.com/51457281/59064234-d8b90280-8877-11e9-9ca0-773306be36c4.PNG)

**Comment by heaths** [comment]
The fixed version has been deployed.

**Comment by BrianDevKit** [comment]
The update works. Thanks
