### ISSUE TITLE
Request: Additional GUID Formats

### ISSUE THREAD

**Issue by BrianDevKit** [heaths/vscode-guid#23]
I would be nice to support the format that fits in C structure definition of GUID with uppercase values.

GUID:
	UINT32  Data1;
	UINT16  Data2;
	UINT16  Data3;
	UINT8   Data4[8]; 

Four hexadecimal values enclosed in braces, where the fourth value is a subset of eight hexadecimal values that is also enclosed in braces: {0x00000000,0x0000,0x0000,{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00}} (X)

**Comment by heaths** [comment]
It does: see format 3 documented on https://marketplace.visualstudio.com/items?itemName=heaths.vscode-guid.

**Comment by BrianDevKit** [comment]
> It does: see format 3 documented on https://marketplace.visualstudio.com/items?itemName=heaths.vscode-guid.

It seems to be only available as a C++ snippet and it doesn't output uppercase in my testing.

**Comment by heaths** [comment]
What compiler are you using? That is valid C.

**Comment by heaths** [comment]
And what do you mean it doesn't output upper case? It's not a textual representation but, in fact, integers that populate a `GUID` C structure. See https://docs.microsoft.com/en-us/previous-versions/aa373931(v=vs.80).

**Comment by heaths** [comment]
Closing since no response was provided after some time. I can reopen if clarification is provided later.
