### ISSUE TITLE
Include option to insert GUID in uppercase

### ISSUE THREAD

**Issue by 101100** [heaths/vscode-guid#6]
Would you accept a PR to add an option to include the GUID in uppercase?  I would do that for both the bare and brace formats, so the menu would be:

```
6b9937c1-f090-4a33-bdd6-f5e6ef54c41b
6B9937C1-F090-4A33-BDD6-F5E6EF54C41B
{6b9937c1-f090-4a33-bdd6-f5e6ef54c41b}
{6B9937C1-F090-4A33-BDD6-F5E6EF54C41B}
static const struct GUID __NAME__ = {0x6b9937c1, 0xf090, 0x4a33, {0xbd, 0xd6, 0xf5, 0xe6, 0xef...
DEFINE_GUID(__NAME__, 0x6b9937c1, 0xf090, 0x4a33, 0xbd, 0xd6, 0xf5, 0xe6, 0xef, 0x54, 0xc4, 0x1b);
```

**Comment by heaths** [comment]
It had crossed my mind, but I was trying to think of another way to do it, like user preference or secondary menu. Nothing sounded good. Just putting them in there would be fine, but please retain the existing order if people have gotten used to it.
