### ISSUE TITLE
Feature request: C++-struct-formatted GUID without the type/macros

### ISSUE THREAD

**Issue by fredemmott** [heaths/vscode-guid#60]
For modern C++, initializer lists are a handy way to put GUIDs in code, e.g. for a raw GUID:

```C++
GUID myGUID {0xfee9d1ce, 0x5baa, 0x4159, {0x91, 0x2e, 0x5f, 0xad, 0x39, 0x3f, 0x0e, 0x5c}
```

or when using [C++/WinRT](https://github.com/microsoft/cppwinrt) (e.g. when using the Windows App SDK):

```C++
winrt::guid myGUID {0xfee9d1ce, 0x5baa, 0x4159, {0x91, 0x2e, 0x5f, 0xad, 0x39, 0x3f, 0x0e, 0x5c};
```

This is essentially the same as option 3, just with everything up to the `{` deleted/replaced:

```
static const struct GUID __NAME__ = {0xfee9d1ce, 0x5baa, 0x4159, {0x91, 0x2e, 0x5f, 0xad, 0x39, 0x3f, 0x0e, 0x5c}};
```

I suggest adding an option that's the right hand side of #3's assignment for the most flexibility

**Comment by heaths** [comment]
Thanks for the suggestion. This was somewhat possible before, but I added a new quick pick item to make it easier to use. Should be processed at https://marketplace.visualstudio.com/items?itemName=heaths.vscode-guid shortly.
