### ISSUE TITLE
Insert GUID in all selections

### ISSUE THREAD

**Issue by SylwesterZarebski** [heaths/vscode-guid#9]
Hi,

  It would be great if extension could replace all selected GUIDs instead of only first one.

Current behaviour:
When chosen insert GUID and had multiple selections, GUID is inserted only in place of first selection.

Wished behaviour:
When had multiple selections, GUID should insert in all of them.

This is desirable when had multiple same GUID, which i want to replace by new one.
Example workflow: select one GUID, <kbd>CTRL+D</kbd> multiple times to select more and then `insert GUID`.

**Comment by heaths** [comment]
Thanks for the suggestion. v1.2.0 is now published with this feature.
